tigrisdata/tigris-client-ts

package-lock.json

protobufjs below 6.11.3 is vulnerable to [prototype pollution](https://learn.snyk.io/lessons/prototype-pollution/javascript/)

fix: Upgrade dependency to avoid security vulnerability

---

src/__tests__/test-service.ts
src/__tests__/tigris.rpc.spec.ts
src/db.ts
src/types.ts
src/utility.ts

Usage
```
const bookSchema: TigrisSchema<IBook> = {
id: {
type: TigrisDataTypes.INT64,
primary_key: {
order: 1,
autoGenerate: true
}
},
author: {
type: TigrisDataTypes.STRING
},
title: {
type: TigrisDataTypes.STRING
},
tags: {
type: TigrisDataTypes.ARRAY,
items: {
type: TigrisDataTypes.STRING
}
}
};
db.createOrUpdateCollection('books', bookSchema)
```
- Unrelated change - updated tx header names.

feat: Added createOrUpdateCollections method on db

---

src/__tests__/test-service.ts
src/__tests__/tigris.rpc.spec.ts
src/collection.ts
src/types.ts

TODO: 
- stitch the generated keys back to docs for both insert and insertOrReplace (in later diff)
Usage:
```
db.getCollection<IBook>('books').insertOrReplace({
author: "author name",
id: 1,
tags: ['science'],
title: 'science book'
});
```

feat: Added InsertOrReplace operation on collection

---

src/__tests__/data/basicCollection.json
src/__tests__/data/multiplePKeys.json
src/__tests__/test-service.ts
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.schema.spec.ts
src/collection.ts
src/db.ts
src/types.ts
src/utility.ts

Return new documents with keys set.
Usage
```
books.insert({
author: "author name",
id: 0, // <---- note 0 to let server generate it.
tags: ['science'],
title: 'science book'
}).then(insertedBook => {
// insertedBook.id is set here
});
```
```
books.insertOrReplace({
author: "author name",
id: 0, // <---- note 0 to let server generate it.
tags: ['science'],
title: 'science book'
}).then(insertedOrReplacedBook => {
// insertedOrReplacedBook.id is set here
});
```
bug fixes:
- schema generation number type fixed to use integer (for int32/int64 fields)

feat!: Return new documents with keys set.

---

.eslintrc.json
package-lock.json
package.json
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.updatefields.spec.ts
src/collection.ts
src/db.ts
src/session.ts
src/types.ts
src/utility.ts

- Fixed transaction implementation (wait for user's async function to finish before commiting/rollbacking transaction. 
- Updated UpdateFields's field `operator` --> `op`
- Added a client side check on `undefinied` filter do not pass delete operation to server.
- Added more explicit `;`
- Fixed readOne() signature to return undefined (from void)
- Prepared for next release.

fix!: Fixed transaction implementation

---

package-lock.json
package.json
src/db.ts
src/types.ts

In case if user passes in `async` function, this will allow them to wait on transaction to finish.
something like
```
await db.transact(async (tx) => {...});
```
(this will now only finish once we resolve the promise) 
- prepare for next release.

fix!: Return a response on transaction

---

package-lock.json
package.json
src/__tests__/test-service.ts
src/__tests__/tigris.filters.spec.ts
src/__tests__/tigris.jsonserde.spec.ts
src/__tests__/tigris.readfields.spec.ts
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.updatefields.spec.ts
src/collection.ts
src/types.ts
src/utility.ts

- Simplified Selector filter for `$eq`
From
```
const filter: SelectorFilter<User> = {
op: SelectorFilterOperator.EQ,
fields: {
name: 'Alice'
}
}
```
to
```
const filter: Selector<User> = {
name: 'Alice'
}
```
- Added a test where primaryKey is generated on server and user may choose to not pass its value from client (0 magic value).
- Prepared for next release.

feat: Simpler SelectorFilter

---

package-lock.json
package.json
src/__tests__/tigris.filters.spec.ts
src/types.ts
src/utility.ts

- Support SimpleSelector within logical filter
Usage:
from
```
const logicalFilter: LogicalFilter<IUser> = {
op: LogicalOperator.OR,
selectorFilters: [
{
op: SelectorFilterOperator.EQ,
fields: {
name: 'alice'
}
},
{
op: SelectorFilterOperator.EQ,
fields: {
name: 'emma'
}
}
]
};
```
to (optionally also support)
```
const logicalFilter: LogicalFilter<IUser> = {
op: LogicalOperator.OR,
selectorFilters: [
{
name: 'alice'
},
{
name: 'emma'
}
]
};
```
- Prepare for next release.

feat: Support simple selector filter within logical filter

---

src/__tests__/data/collectionWithObjectArrays.json
src/__tests__/data/collectionWithPrimitiveArrays.json
src/__tests__/data/multiLevelObjectArray.json
src/__tests__/data/multiLevelPrimitiveArray.json
src/__tests__/data/nestedCollection.json
src/__tests__/test-service.ts
src/utility.ts

Because some programming languages does not allow _id as the field name in their model.

fix: Renamed autogenerated _id to id

---

package-lock.json
src/__tests__/search/search.types.spec.ts
src/__tests__/tigris.utility.spec.ts
src/collection.ts
src/search/types.ts
src/utility.ts

- Updated the latest api changes
- Moved Pagination to its own object to in sync with Java/Go SDK
- Removed default pagination parameters from search request, they won't be sent unless user explicitly sends them. This is to enable streaming responses.
- Added docs for Search related stubs

chore: sync with latest search api

---

README.md
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.utility.spec.ts
src/collection.ts
src/search/types.ts
src/utility.ts

- More user-friendly version of faceting api, either of following works for `facetQuery`:
```typescript
const request: SearchRequest<User> = {
q: "Jania",
facetQuery: ["firstName", "lastName"],  // implicit default faceting options
};
```
OR
```typescript
const request: SearchRequest<User> = {
q: "Jania",
facetQuery: {
"firstName" : { "size": 10 }, 
"lastName": { "size": 10 }
}
};
```

feat: A simplified faceting api

---

src/collection.ts
src/search/types.ts

To create a search request:
```
const request: SearchRequest<IBook> = {
q: "philosophy",
includeFields: ["one", "two"],
excludeFields: ["three"]
};
```

refactor: Field selection api for search

---

package-lock.json
package.json
src/tigris.ts

Fetching authorization header and making actual gRPC call had race condition, this PR fixes it so that the gRPC call gets made once the authorization token is made available.

fix: Fixed the race-condition of authorization header calls

---

src/db.ts
src/session.ts
src/utility.ts

grpc NodeJS implementation high level client doesn't support reading response header. For one specific method (beginTransaction) - using lower level API call to read back the response headers.

feat: Supply cookies back for interactive tx for sticky routing

---

package-lock.json
src/tigris.ts

Default to secure channel if `insecureChannel` is not explicitly set in config.

fix: Do not require insecure config option, fallback to secure channel

---

src/__tests__/cursor/cursor.spec.ts
src/__tests__/test-service.ts
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.utility.spec.ts
src/collection.ts
src/cursor/abstract-cursor.ts
src/cursor/cursor.ts
src/error.ts
src/utility.ts

Removing callbacks for streaming APIs and instead using iteration to read results. For ex:
```typescript
const booksIterator = db1.getCollection<IBook>("books").findMany();
for await (const book of booksIterator) {
bookCounter++;
expect(book.author).toBe("Marcel Proust");
}
expect(bookCounter).toBe(4);
```
> This would be a breaking API change and require changes across the usages

feat: non-streaming search api with pagination

---

src/__tests__/cursor/cursor.spec.ts
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.utility.spec.ts
src/collection.ts
src/cursor/abstract-cursor.ts
src/search/types.ts
src/types.ts
src/utility.ts

- Transform read cursor to native [Node.js readable streams](https://nodejs.org/api/stream.html#class-streamreadable)
- Rename `insert` to `insertOne`, to have consistent apis:
- `insertOne`, `insertMany`, `findOne`, `findMany`
- Allow `collation` option for update and delete queries.
- Code documentation on collection APIs

refactor: Updates for collections API

---

package-lock.json
src/tigris.ts

For secure channels add the default metadata for every outbound calls.

feat: Add default metadata for secure channels

---

src/consumables/utils.ts
src/topic.ts

Fixing following warnings from lgtm.com to gain back `A+`
- The parameter 'ProtoSubscribeResponse' has type 'any', but its name coincides with the imported type ProtoSubscribeResponse.
- The parameter 'TResp' has type 'any', but its name coincides with the type parameter TResp.
Updated api submodule.

refactor: Fixed typescript warnings

---

package-lock.json
package.json
src/tigris.ts

- Tigris config supports reading env variables, This PR takes care of loading env variables and not rely on app to take care of it. 
- Upgrade grpc-tools version.
- Upgrade API submodule.

fix: Load env variables

---

src/__tests__/data/invalidModels/multiExport/users.ts
src/__tests__/data/models/embedded/users.ts
src/__tests__/utils/manifest-loader.spec.ts
src/error.ts
src/utils/manifest-loader.ts

- Only allow a single `export` for `TigrisSchema` type from schema definition file

fix: Single TigrisSchema per model file

---

.github/workflows/release.yaml
package.json
scripts/publishLatestRelease.sh
scripts/verifyReleaseNeeded.sh

Current releases are only getting published to `beta` tag. Added a step after a release gets published to `beta` it should also gets published to `latest` tag. This is temporary until we have our first stable release and can be removed then.
The script should fail publishing to `latest` if there is already a stable release.

chore: Publish beta releases to @latest tag temporarily

---

.github/workflows/pre-release.yaml
.github/workflows/release.yaml
package.json

This should "only" publish beta versions to `latest` tag and stop publishing to "beta" tag.

fix: Using latest channel for beta releases

---

src/__tests__/data/basicCollection.json
src/__tests__/data/basicCollectionWithObjectType.json
src/__tests__/data/collectionWithObjectArrays.json
src/__tests__/data/collectionWithPrimitiveArrays.json
src/__tests__/data/multiLevelObjectArray.json
src/__tests__/data/multiLevelPrimitiveArray.json
src/__tests__/data/multiplePKeys.json
src/__tests__/data/nestedCollection.json
src/utility.ts

Server internally uses documents collection type as default. Removed it in absence of `message` collection type.

Remove collection type

---

src/tigris.ts

Client fails to start if variable is defined but empty string.

Fix empty URL setting

---

src/__tests__/data/decoratedModels/users.ts
src/__tests__/tigris.filters.spec.ts
src/decorators/tigris-field.ts
src/error.ts
src/utility.ts

- Now decorated schema can automatically interpret `Date` fields as `DATE_TIME` in schema. E.g.-, [this unit test](https://github.com/tigrisdata/tigris-client-ts/pull/194/files#diff-8349b4caf0b5bb16362a7cf27f05522b35bdcfb5521114f9b4befd5dc17c1255R33-R34)
- Users can still explicitly specify a schema type of DATE_TIME to be used internally as string. See [this](https://github.com/tigrisdata/tigris-client-ts/pull/194/files#diff-1b1c836ae8f3e670b3567eb76d3a52ebb591b8e45076cd92be50c183a73508fcR342)
- `Date` objects can be used  as it is in Filters.

feat: Support for Date types in schema and filter

---

src/__tests__/test-cache-service.ts
src/__tests__/tigris.rpc.spec.ts
src/cache.ts
src/tigris.ts
src/types.ts
src/utility.ts

Surfacing Caches API to TypeScript SDK.
```
// create cache
const c1 = await tigris.createCacheIfNotExists("c1");
// set
await c1.set("k1", "val1");
await c1.set("k2", 123");
await c1.set("k3", true);
await c1.set("k4", {"a": "A", "n": 123});
// get
const value = await c1.get("k1").value;
// del
await c1.del("k1");
// keys
const keys: string[] = await c1.keys();
// list caches
const caches = await tigris.listCaches();
// delete cache
await tigris.deleteCache("c1");
```
- Unit test with mock Tigris server (included)
- Tested manually with starter app against Tigris server.

feat: Added Caches API

---

src/__tests__/test-cache-service.ts
src/__tests__/tigris.rpc.spec.ts
src/cache.ts
src/types.ts

- Added getSet method for cache for TypeScript SDK.
- Made set options fields optional.
```
const c1 = tigris.getCache("c1");
await c1.set("k1", "v1");
const getSetResp = c1.getSet("k1", "v2");
console.log(getSetResp.old_value); // "v1"
```
- Unit tested.

feat: Implemented getSet method for cache

---

.github/workflows/pre-release.yaml
.github/workflows/release.yaml

This PR should fix the failing `release-test` workflow

ci: Using node 18 for semantic release

---

src/__tests__/fixtures/json-schema/vacationRentals.json
src/__tests__/fixtures/schema/vacationRentals.ts
src/schema/decorated-schema-processor.ts
src/types.ts
src/utility.ts

- Introduced a way to mark a field both with `createdAt` and `updatedAt`
- Renamed the generator functions under `Generated` enum
- unit tests
TIG-810

feat: default timestamp to mark a field with both createdAt or updatedAt

---

src/__tests__/test-service.ts
src/__tests__/tigris.rpc.spec.ts
src/cache.ts
src/collection.ts
src/constants.ts
src/db.ts
src/index.ts
src/session.ts
src/tigris.ts
src/types.ts

Returning response statuses for users to assert against:
```
DeleteResponse:
status: "deleted"
UpdateResponse:
status: "updated"
CreateResponse:
status: "created"
```
Another option is to replace `status: Status` with `success: boolean` for easy assertion. Opinions?
- Essentially these operations can have a `success: true`:
- How will it work if updateMany() succeeds partially and returns num of updated rows?
- DDL operations  (drop collection. create/delete branch etc.) or cache.set() can instead return a `Promise<boolean>`. Having them return an object later would be a breaking change.
- Tests

refactor: Tigris operations to use enums for Status

---

src/__tests__/consumables/cursor.spec.ts
src/__tests__/tigris.rpc.spec.ts
src/db.ts
src/error.ts
src/tigris.ts

- `getDatabase()` is sync again and made `initializeDB()` as a standalone method in `DB` as `initializeBranch()`
- Users will have to explicitly initialize branch, core functionality stays same
- unit tests

feat: Sync `getDatabase()` call

---

src/__tests__/test-cache-service.ts
src/__tests__/tigris.rpc.spec.ts
src/cache.ts
src/consumables/cursor.ts
src/types.ts

Cache operation to list all keys returns Cursor and allows client to iterate on it in streaming manner.
```
const c1 = tigris.GetCache("c1);
const keysCursor = await c1.keys();
for await (const keys of keysCursor) {
// keys is of type Array<String>
console.log(keys);
}
```
Mocked integration tests are included in this PR.

feat: Cache keys streams response

---

src/__tests__/tigris.utility.spec.ts
src/utility.ts

- Will handle nerfing of branch names on server side as this may lead to same DB branch being used for multiple git branches
- Only impacts how we generate the branch names for preview deployments
- Unit tests

fix: removing branch name nerfing to handle it on server

---

README.md

Updated links to discord instead of slack. 
I'm not sure if I generated the discord correctly, could someone who generated the slack one just verify it.

fix: switch to discord in community links

---

src/__tests__/search/search.types.spec.ts
src/__tests__/test-search-service.ts
src/__tests__/tigris.search.spec.ts
src/search/result.ts

- facets in `SearchResult` being an ES6 map was not getting serialized to string
- changing them to object serializes it to string correctly
```diff
- private readonly _facets: ReadonlyMap<string, FacetCountDistribution>;
+ export type Facets = { [key: string]: FacetCountDistribution };
+ private readonly _facets: Facets;
```
```
console.log(JSON.stringify(result.facets));
{"author":{"_counts":[],"_stats":{"_avg":4.5,"_count":0,"_max":0,"_min":0,"_sum":0}}}
```
- Existing unit tests
closes #248

fix: Making search facets an object instead of ES6 map

---

src/__tests__/test-search-service.ts
src/__tests__/tigris.search.spec.ts
src/search/result.ts
src/search/search-index.ts

- `getMany()` and `getOne()` APIs on search index to return metadata along with the document
```diff
- getMany(ids: Array<string>): Promise<Array<T>>;
+ getMany(ids: Array<string>): Promise<Array<IndexedDoc<T>>>;
```
where IndexedDoc is:
```ts
class IndexedDoc<T> {
document: T;
meta: DocMeta | undefined;
}
```
- Unit tests for both `searchDocs` and `getDocs`

feat: GetDocs on search index to return metadata along with document

---

src/__tests__/test-search-service.ts
src/search/result.ts

- Merging IndexDoc to `SearchHit` proto structure itself
- Existing unit tests were already validating deserialization for both `SearchHit` and `IndexDoc`

fix: removing references for IndexedDoc proto message

---

src/__tests__/fixtures/json-schema/orders.json
src/__tests__/fixtures/json-schema/search/orders.json
src/__tests__/fixtures/schema/orders.ts
src/__tests__/fixtures/schema/search/orders.ts
src/__tests__/test-search-service.ts
src/decorators/metadata/decorator-meta-storage.ts
src/decorators/metadata/field-metadata.ts
src/decorators/tigris-field.ts
src/decorators/tigris-search-field.ts
src/decorators/utils.ts
src/schema/decorated-schema-processor.ts
src/search/types.ts
src/types.ts
src/utility.ts

- Enables annotating collection fields as search index fields
- [orders.ts](https://github.com/tigrisdata/tigris-client-ts/pull/265/files#diff-db704cf226bd5733e2d449c7f142614faba3079cd97ade6a82cf91f7f2ea19a7) represents a collection data model with search fields and [orders.json](https://github.com/tigrisdata/tigris-client-ts/pull/265/files#diff-7b1ce5c287129caf64eab185fea580874a81525a156c7d40f8c849966d9e1fa5) is the generated json schema sent to the server
- Unit tests
closes #259

feat: Search annotations on a collection

---

src/__tests__/index.spec.ts
src/__tests__/tigris.readfields.spec.ts
src/__tests__/tigris.search.spec.ts
src/__tests__/tigris.utility.spec.ts
src/collection.ts
src/search/query.ts
src/search/search-index.ts
src/types.ts
src/utility.ts

```diff
- const matchAll: SearchQuery<Student> = { q: "" };
+ const matchAll: SearchQuery<Student> = { };
```
```diff
- searchFields?: Array<string>;
+ searchFields?: DocumentPaths<T>;
- includeFields?: Array<string>;
+ includeFields?: DocumentPaths<T>;
- excludeFields?: Array<string>;
+ excludeFields?: DocumentPaths<T>;
- export type FacetFieldOptions = {
- 	[key: string]: FacetQueryOptions;
- };
+ export type FacetFieldOptions<T> = DocumentFields<T, FacetQueryOptions>;
- export type FacetFields = Array<string>;
+ export type FacetFields<T> = DocumentPaths<T>;
- export type ReadFields = {
-	include?: Array<string>;
-	exclude?: Array<string>;
-};
+ export type ReadFields<T> = {
+	include?: DocumentPaths<T>;
+	exclude?: DocumentPaths<T>;
+};
-export type SortField = {
-	field: string;
- …
```

feat: static type checking for query constructs

---

src/search/result.ts

- Having `undefined` is redundant and will force users to type check/cast on consumption
- Unit tests

fix: removing redundant "undefined" types

---

src/__tests__/tigris.updatefields.spec.ts
src/types.ts

- Allows setting embedded documents and arrays in update fields
```ts
const updatedPublisher: Publisher = {
totalPublished: 24,
name: "Urban books"
}
const publisherUpdate: UpdateFields<Books> = {
$set: {
publisher: updatedPublisher
}
}
const categoryUpdate: UpdateFields<Books> = {
$set: {
categories: ["classic", "literature"]
}
}
```
- Unit tests
closes #271

fix: Allow object types for updating a document

---

src/__tests__/fixtures/json-schema/vacationRentals.json
src/__tests__/fixtures/schema/vacationRentals.ts
src/__tests__/tigris.schema.spec.ts
src/utility.ts

- Free flow objects were not including empty `properties: {}` on serializing the schema
- Unit tests

fix: Empty properties obj on free flow objects

---

package-lock.json
package.json
src/__tests__/tigris.jsonserde.spec.ts

fix: Fix for json-bigint bug https://github.com/sidorares/json-bigint/issues/49 where it tries to parse float numbers as BigInt
Use the fixed version of the library and add a test
Test failure before the library update
```
$ npx jest src/__tests__/tigris.jsonserde.spec.ts
FAIL  src/__tests__/tigris.jsonserde.spec.ts
JSON serde tests
✕ jsonSerDe (2 ms)
✓ jsonSerDeStringAsBigInt
✓ jsonSerDeNativeBigInt (1 ms)
✓ jsonSerDeNativeBigIntNested
● JSON serde tests › jsonSerDe
SyntaxError: Cannot convert -73.96340000000001 to a BigInt
at BigInt (<anonymous>)
215 | 	jsonStringToObj<T>(json: string, config: TigrisClientConfig): T {
216 | 		const JSONbigNative = json_bigint({ useNativeBigInt: true });
> 217 | 		return JSONbigNative.parse(json, (k, v) => {
| 		                     ^
218 | 			// convert …
```

fix: Fix for json-bigint bug

---

src/__tests__/fixtures/json-schema/orders.json
src/__tests__/fixtures/json-schema/search/matrices.json
src/__tests__/fixtures/json-schema/search/orders.json
src/__tests__/fixtures/schema/orders.ts
src/__tests__/fixtures/schema/search/matrices.ts
src/__tests__/fixtures/schema/search/orders.ts
src/schema/decorated-schema-processor.ts

Arrays of objects and nested arrays only support index-related tags at the parent level.
```
// { "field1": { "type": "object", "properties": { "name": { "type": "string" } }, "searchIndex": true } - not supported
// { "field1": { "type": "object", "properties": { "name": { "type": "string", "searchIndex": true } } } - supported
// searchIndex, sort and facet tags cannot be defined within a nested array
// { "field1": { "type": "array", "items": { "type": "object", "properties": { "name": { "type": "string", "searchIndex": true } } } } - not supported
// { "field1": { "type": "array", "items": { "type": "object", "properties": { "name": { "type": "string" } } }, "searchIndex": true } - supported
```
Unit tests

Arrays of objects and nested arrays only support index related tags at the parent level

---

src/__tests__/fixtures/json-schema/search/matrices.json
src/__tests__/fixtures/json-schema/vacationRentals.json
src/__tests__/fixtures/schema/search/matrices.ts
src/__tests__/fixtures/schema/vacationRentals.ts
src/__tests__/search/schema.spec.ts
src/__tests__/search/search.types.spec.ts
src/__tests__/tigris.schema.spec.ts
src/__tests__/tigris.utility.spec.ts
src/decorators/tigris-field.ts
src/decorators/tigris-search-field.ts
src/error.ts
src/schema/decorated-schema-processor.ts
src/search/query.ts
src/search/result.ts
src/search/types.ts
src/types.ts
src/utility.ts

- Introducing ability to define a vector type of field in a search index schema:
```ts
@SearchField({ dimensions: 4, sort: false })
relevance: Array<number>;
```
or a collection schema
```ts
@Field({ dimensions: 3, default: [1.0, 1.0, 1.0] })
relevance: number[];
```
which gets serialized to:
```json
"relevance": {
"type": "array",
"dimensions": 4,
"format": "vector",
"searchIndex": true,
"sort": false
}
```
and
```json
"relevance": {
"type": "array",
"dimensions": 3,
"format": "vector",
"default": [1.0, 1.0, 1.0]
}
```
- Also, lets user query against these vector fields:
```ts
const query: SearchQuery<Movies> = {
vectorQuery: {
"relevance": [0.4, -0.15, 0.9],
},
};
```
- Unit tests
closes #288

feat: Vector fields and vector search query

---

src/__tests__/fixtures/json-schema/movies.json
src/__tests__/fixtures/schema/movies.ts
src/schema/decorated-schema-processor.ts

Fix a bug where for a collection schema, the collection field and schema field options were not merged properly.
If there was a field defined as follows:
```
@SearchField(TigrisDataTypes.ARRAY, { elements: TigrisDataTypes.STRING, facet: true })
@Field(TigrisDataTypes.ARRAY, { elements: TigrisDataTypes.STRING })
genres: Array<string>;
```
The field annotation was overwriting the SearchField annotation.
Now with this change, we merge the options in the two annotations.
If a field has a SearchField annotation and a Field annotation, merge the field options.
Unit tests

Fix a bug with collection schema

---

src/__tests__/index.spec.ts
src/__tests__/tigris.filters.spec.ts
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.utility.spec.ts
src/search/query.ts
src/types.ts
src/utility.ts

- `type` is optional for **FacetQueryOptions**
- Filter specification for nested fields supports both - dot notation and nested objects
- Unit tests
BREAKING CHANGE: Filters are no more generics

feat: dot notation for filters 

---

src/__tests__/fixtures/json-schema/search/orders.json
src/__tests__/fixtures/schema/search/matrices.ts
src/__tests__/fixtures/schema/search/orders.ts
src/schema/decorated-schema-processor.ts
src/search/types.ts
src/utility.ts

A string field can be annotated in a search index and that field value will be used as the document ID
Unit tests

Add support for id annotation on search index

---

src/__tests__/tigris.rpc.spec.ts
src/collection.ts

- Added a check,  if the gRPC insert response does not contain the createdAt timestamp field value then add those respective field values from the response metadata or else ignore.
- Identified createdAt timestamp fields with the help of DecoratorMetaStorage for the specific collection.
/claim #245 
- Added the individual test cases for this scenario.
Fixes #245

fix: set createdAt timestamp field value on collection insert if not exists

---

src/__tests__/fixtures/json-schema/students.json
src/__tests__/fixtures/schema/movies.ts
src/__tests__/fixtures/schema/student.ts
src/__tests__/tigris.schema.spec.ts
src/decorators/tigris-primary-key.ts
src/error.ts
src/schema/decorated-schema-processor.ts

- Order in the primaryKeyOptions is not required when there is only one primary key in the collection.
- Order is required when there are multiple primary keys.
#242 
/claim #242
- npm run test , Added individual test cases. 
Fixes: #242

refactor: primaryKeyOptions as optional if there is only one primary key for collection

---

src/__tests__/fixtures/schema/student.ts
src/__tests__/tigris.rpc.spec.ts
src/__tests__/tigris.schema.spec.ts
src/error.ts
src/types.ts
src/utility.ts

( Refactored as per comments on this [PR](https://github.com/tigrisdata/tigris-client-ts/pull/308#issuecomment-1511987616) )
- Specifying 'order' is optional if there is only one primary key for collection when the schema defined through the interfaces. ( if not specified, default order is 1 )
- Order is required when there are multiple primary keys.
- Moved the test example class to the spec file.
- Related Issue:  https://github.com/tigrisdata/tigris-client-ts/pull/308#issuecomment-1511987616
Not sure, but we can specify in the docs as well.
- [] Yes, and here is the link: _please create an issue in [tigris-docs](https://github.com/tigrisdata/tigris-docs/issues) repo
and link here as `tigrisdata/tigris-docs#123`_
- [] No

refactor: primary key order optional under interface defined schema

---

src/db.ts

Fixes dropCollections to wait for all the collections to be dropped before resolving the promise.
The dropCollections was not waiting for all the collections to be dropped before resolving. This was causing a race condition. 
- Closes #
and link here as `tigrisdata/tigris-docs#123`_

fix: DropCollections waits for all

---

src/__tests__/tigris.filters.spec.ts
src/types.ts

Add the following missing comparison operators:
- $not
- $contains
- $regex
/claim #325
https://github.com/tigrisdata/tigris-client-ts/issues/325
- Related Issue #325
- Closes #325
[tigrisdata/tigris-docs#123](https://github.com/tigrisdata/tigris-docs/issues/385)

Adding missing comparison operators to client

---

.github/workflows/pre-release.yaml
.github/workflows/ts-ci.yml

- Allows running `ts-ci` workflow on pull requests coming from forks.
- Replaces trigger for **pre-release** workflow to be `pull_request`. As per [following recommendation](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), the pre-release should not be needing write permissions as its a dry run:
```
Workflows triggered via pull_request_target have write permission to the target repository. They also have access to target repository secrets. The same is true for workflows triggered on pull_request from a branch in the same repository, but not from external forks. The reasoning behind the latter is that it is safe to share the repository secrets if the user creating the PR has write permission to the target repository already.
```

ci: trigger workflows on pull requests

---

src/__tests__/test-search-service.ts
src/__tests__/tigris.search.spec.ts
src/search/search.ts

Adds a new method, `createOrUpdateIndexFromClass` that allows providing a name for the index that will override the one in the model.
- Closes #

Add new index creation method that allows overriding index name

---

src/__tests__/search/search.spec.ts
src/__tests__/tigris.search.spec.ts
src/search/search.ts

- Three ways to create a search index:
1. Using decorated model class: `search.createOrUpdateIndex(MyDecoratedModelClass)`
2. Using name and interface: `search.createOrUpdateIndex("name", MyIndexSchemaInterface)`
3. Using name and decorated model class: `search.createOrUpdateIndex("name", MyDecoratedModelClass)`
- Closes #

feat: Pass index name along with decorated class

---

src/__tests__/tigris.readfields.spec.ts
src/__tests__/tigris.utility.spec.ts
src/collection.ts
src/search/query.ts
src/types.ts
src/utility.ts

- Added static binding for query constructors ( Search, Find & Update) 
- Refactored DocumentPaths type (the previous version was not able to flatten the objects which were defined as optional)
/claim #318
- Closes #318 

feat: static type binding for query

---

src/__tests__/tigris.search.spec.ts
src/schema/decorated-schema-processor.ts
src/search/search.ts

Solves #343. Return a more descriptive error message when the `@TigrisSearchIndex` decorator is not set. 
- Related Issue #343
- Closes #343
/claim #343

fix: Handle missing decorator for model

---

src/__tests__/tigris.filters.spec.ts
src/types.ts

Currently, filters are strongly typed. This presents an issue for complex types like array, where we may want to do queries such as `contains` on array type fields.
- Closes #

fix: relax filter type checking

---

src/__tests__/tigris.rpc.spec.ts
src/db.ts

Some calls to the server return useful error messages by default. A few operations do not.
The initializeBranch functionality for instance, explicitly handles similar errors and 
logs a useful error message when branch already exists.
Since any operation on a non-existing project will fail I explored the possibility of finding a "central"
location to log a useful error message. I didn't find any. My only thought was to modify the response 
returned by the "server"
In this PR I only modified the createBranch method to log a useful error message when project does not
exist. The same method is called when initializing branches so this change caters for both. 
Other methods (registerSchemas) where similar errors occur have useful error messages 
returned from the api at the moment.
- Related …

chore: Improve error logging when project name in use does not exist on Tigris

---

src/__tests__/fixtures/json-schema/search/orders.json
src/__tests__/fixtures/schema/search/orders.ts
src/__tests__/search/schema.spec.ts
src/decorators/metadata/search-index-metadata.ts
src/decorators/tigris-search-index.ts
src/schema/decorated-schema-processor.ts
src/search/search.ts
src/types.ts
src/utility.ts

- Optionally specify tokens to split the texts, texts will be tokenized by space, new-line and specified characters.
```ts
@TigrisSearchIndex(ORDERS_INDEX_NAME, { tokenSeparators: ["/"] })
export class Order {
// fields
}
```
- Closes #

feat: optional token separators for search index schema
