- package-lock.json
- package.json
- src/__tests__/test-service.ts
- src/__tests__/tigris.spec.ts
- src/tigris.ts
- src/types.ts
Added interactive transaction API.
Usage 1:
```
const db = tigris.getDatabase('my-db');
const books = txDB.getCollection<IBook>('books')
txDB.transact(tx => {
books.insert(
{
id: 1,
author: 'Alice',
title: 'Some book title'
},
tx
)
});
```
Usage 2:
```
const db = tigris.getDatabase('my-db');
const books = txDB.getCollection<IBook>('books')
db.beginTransaction().then(tx => {
try{
books.insert(
{
id: 1,
author: 'Alice',
title: 'Some book title'
},
tx
)
tx.commit();
} catch(error) {
tx.rollback();
}
})
> feat: Added Transaction API

- .editorconfig
- package-lock.json
- package.json
- src/__tests__/test-service.ts
- src/__tests__/tigris.spec.ts
- src/collection.ts
- src/db.ts
- src/session.ts
- src/tigris.ts
- src/types.ts
- src/utility.ts
This pull request refactors the codebase to make contributions faster by
- Updating the file structure by moving modules into it's own files.
- Make types to be more strict.
Next to that, it also 
- Fixes the dependencies
- Adds `editor.config` for fast formatting
> refactor: Improves file structure and typings

- package-lock.json
- package.json
This PR adds scripts in package.json that allows us to publish the built package to npmjs.com
> chore: Adds scripts in package.json for publishing to npmjs.com

- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.spec.ts
- src/collection.ts
- src/types.ts
- src/utility.ts
Type aware filters
Usage:
For the data model
```
export interface IUser extends TigrisCollectionType {
id: BigInt;
name: string;
balance: number;
}
```
SelectorFilter 
```
const filter1: SelectorFilter<IUser> = {
op: SelectorFilterOperator.EQ,
fields: {
name: 'Alice',
balance: 123.456
}
}
```
LogicalFilter
```
const logicalFilter: LogicalFilter<IUser> = {
op: LogicalOperator.OR,
selectorFilters: [
{
op: SelectorFilterOperator.EQ,
fields: {
name: 'alice'
}
},
{
op: SelectorFilterOperator.EQ,
fields: {
name: 'emma'
}
}
]
}
```
Credit: https://stackoverflow.com/q/72482290/3833308
> feat!: Fluent filters

- src/__tests__/tigris.filters.spec.ts
- src/__tests__/tigris.jsonserde.spec.ts
- src/__tests__/tigris.readfields.spec.ts
- src/__tests__/tigris.updatefields.spec.ts
TODO: fix the linter warnings later.
> fix: broke the tests further into individual files

- .eslintrc.json
- README.md
- package-lock.json
- src/__tests__/test-service.ts
- src/__tests__/tigris.filters.spec.ts
- src/__tests__/tigris.jsonserde.spec.ts
- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.schema.spec.ts
- src/collection.ts
- Added explicit `;` .
- Removed unused variables.
- Updated README.
- Preparation for next release.
> chore: Improved code quality

- package.json
- src/__tests__/tigris.rpc.spec.ts
- src/collection.ts
- src/tigris.ts
- Updated readOne method  signature friendly for more common usecase.
- Fixed explicit `;`.
> fix! updated read signature for more common use cases

- package-lock.json
- package.json
- src/__tests__/tigris.rpc.spec.ts
- src/db.ts
```
db.createOrUpdateCollection('users', userSchema).then (users => {
})
```
- prepare for next release.
> fix: Return collection upon creation

- src/__tests__/tigris.updatefields.spec.ts
- src/collection.ts
- src/types.ts
- src/utility.ts
from:
```
users.update(
{
userId: bunny.userId,
},
{
op: UpdateFieldsOperator.SET,
fields: {
name: "Jania McGrover",
},
}
);
```
to
```
users.update(
{
userId: bunny.userId,
},
{
name: "Jania McGrover",
}
);
```
> feat: Simpler UpdateFields

- src/__tests__/test-service.ts
- src/collection.ts
- src/session.ts
- src/utility.ts
> fix: Moved transaction details to headers

- .eslintrc.json
- package-lock.json
- src/__tests__/search/tigris.types.spec.ts
- src/__tests__/test-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/collection.ts
- src/search/types.ts
- src/search/utility.ts
```json
{
"q": "Steve",
"search_fields": [
"first_name",
"last_name"
],
"filter": {
"$or": [
{
"country": {
"$eq": "USA"
}
},
{
"country": "UK"
}
],
"$and": [
{
"last_name": {
"$ne": "Ballmer"
}
},
{
"last_updated": {
"$gte": "2018-10-29 10:02:48"
}
},
{
"last_updated": {
"$lt": "2020-10-29 10:02:48"
}
}
]
},
"facet": {
"first_name": {
"type": "value",
"size": 20
}
},
"sort": [   ],
"fields": []
}
```
```json
{
"hits": [
{
"doc": {},
"metadata": {}
}
],
"facet": {
"field": {
"counts": [],
"stats": {}
}
},
"meta": {
"found": 12345,
"page": {
"current": 1,
"total": 5,
"per_page": 10
}
}
}
```
> feat: Tigris search client

- src/__tests__/tigris.rpc.spec.ts
- src/collection.ts
- src/types.ts
- src/utility.ts
readOne() --> findOne()
read() --> findMany() with return type batch of documents, findManyStream() with a callback.
> feat! Updated read method signatures

- src/tigris.ts
Tigris server [will support](https://github.com/tigrisdata/tigris/pull/441) application based client credentials for authentication and authorization. This PR updates the client support to adapt to that mechanism.
> feat: Support application authentication

- src/utility.ts
> fix: removed post processing that incorrectly added primary_key for messages

- README.md
- package.json
- src/topic.ts
> chore: next release version

- src/__tests__/consumables/cursor.spec.ts
- src/__tests__/tigris.rpc.spec.ts
- src/tigris.ts
Removed option for `insecure` client from config.
> feat: Remove insecure from config

- src/tigris.ts
* No explicit config required
* By default point to hosted platform
* Allow to configure id/secret/token/url from environment
* Insecure connections to localhost only
> Configuration enhancements

- src/tigris.ts
> fix: Fixed localhost detection

- package-lock.json
- package.json
- src/tigris.ts
- When user is heavy on pub-sub usecase and in case if there is no message exchange for long - underlying http connection will get timed out. This is to keep it alive by making periodic ping to server.
- updated api submodule.
> fix: Added a periodic ping mechanism

- src/__tests__/tigris.rpc.spec.ts
- src/collection.ts
> feat: Removing change events support

- src/__tests__/tigris.rpc.spec.ts
- src/tigris.ts
Empty commit to trigger a release
> fix: log the server url

- src/collection.ts
- src/types.ts
Removed code related to event streaming for redesign.
> Cleanup event streaming

- src/__tests__/utils/manifest-loader.spec.ts
- src/tigris.ts
- src/utils/manifest-loader.ts
Automatic schema management now expects collections for only a single database.
> Register schema now requires database name to be passed.

- src/__tests__/test-service.ts
- src/__tests__/tigris.utility.spec.ts
- src/collection.ts
- src/db.ts
- src/session.ts
- src/tigris.ts
- src/utility.ts
See https://github.com/tigrisdata/tigris-api/pull/159
> refactor! [BREAKING] Switching to Project paradigm

- .prettierignore
- src/__tests__/consumables/cursor.spec.ts
- src/__tests__/schema/decorator-processor.spec.ts
- src/__tests__/search/search.types.spec.ts
- src/__tests__/test-observability-service.ts
- src/__tests__/test-service.ts
- src/__tests__/tigris.filters.spec.ts
- src/__tests__/tigris.jsonserde.spec.ts
- src/__tests__/tigris.readfields.spec.ts
- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.schema.spec.ts
- src/__tests__/tigris.updatefields.spec.ts
- src/__tests__/tigris.utility.spec.ts
Including linting for unit tests, no other changes.
> chore: prettify unit tests only

- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.utility.spec.ts
- src/collection.ts
- src/error.ts
- src/search/types.ts
- src/types.ts
- src/utility.ts
This is a final work on revamping Collection API. 
```ts
insertMany(docs: Array<T>, tx?: Session): Promise<Array<T>>;
insertOne(doc: T, tx?: Session): Promise<T>;
insertOrReplaceMany(docs: Array<T>, tx?: Session): Promise<Array<T>>;
insertOrReplaceOne(doc: T, tx?: Session): Promise<T>;
updateMany(query: UpdateQuery<T>): Promise<UpdateResponse>;
updateMany(query: UpdateQuery<T>, tx: Session): Promise<UpdateResponse>;
updateOne(query: UpdateQuery<T>): Promise<UpdateResponse>;
updateOne(query: UpdateQuery<T>, tx: Session): Promise<UpdateResponse>;
deleteMany(query: DeleteQuery<T>): Promise<DeleteResponse>;
deleteMany(query: DeleteQuery<T>, tx: Session): Promise<DeleteResponse>;
deleteOne(query: DeleteQuery<T>): Promise<DeleteResponse>;
deleteOne(query: DeleteQuery<T>, tx: Session): …
```
> feat: Reworked collection APIs

- src/collection.ts
We can leverage some of the new JS/TS functionality to refactor the internal code of the collection library. 
The main change is using `async/await` instead of promises. This is a lot easier to read. 
I've also used [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) instead of checking for `undefined`.
```
iteratorResult?.value; // Will return undefined if value doesn't exist otherwise value
```
All the existing tests should pass
None
> chore: Code refactoring in the collections

- package-lock.json
- package.json
- src/__tests__/consumables/cursor.spec.ts
- src/__tests__/test-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.utility.spec.ts
- src/__tests__/utils/env-loader.spec.ts
- src/collection.ts
- src/db.ts
- src/error.ts
- src/session.ts
- src/tigris.ts
- src/types.ts
- src/utility.ts
- src/utils/env-loader.ts
`getDatabase()` operation is async now as it may check and automatically create database branch
```diff
const client = new TigrisClient();
- const db = client.getDatabase();
+ const db = await client.getDatabase();
```
```
export TIGRIS_DB_BRANCH = "staging"
// or
config = {projectName: "MyProject", branch: "staging"};
```
throws error if branch does not exist already
```
export TIGRIS_DB_BRANCH = "some_prefix_${VERCEL_GIT_COMMIT_REF}"
// or config
// following is set by Vercel (same for netlify)
export VERCEL_GIT_COMMIT_REF = "featureBranch"
```
Will attempt to create a `some_prefix_featureBranch` branch if does not exist already
- All DB ops on a branch, default - `main`
Determine the project root path using `appRootPath` lib and load dotenv files based on **NODE_ENV**
```
export …
```
> feat: Database branching

- src/db.ts
- Fixes a bug where `describe()` queries were happening before a branch was created
- Unit tests
> fix: Bug where describe DB was using unavailable branch name

- .eslintrc.json
- package-lock.json
- package.json
- src/__tests__/tigris.rpc.spec.ts
- src/cache.ts
- src/constants.ts
- src/consumables/iterable-stream.ts
- src/db.ts
- src/decorators/options/embedded-field-options.ts
- src/error.ts
- src/session.ts
- src/tigris.ts
- src/types.ts
- src/utility.ts
- Setting up a linter plugin for `docstrings` - https://tsdoc.org/pages/packages/eslint-plugin-tsdoc/
- Will run with default `npm run lint` command
- Unit tests
- `npm run lint`
> chore: Linting on docs

- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.utility.spec.ts
- src/db.ts
- src/error.ts
- src/utility.ts
- Requiring branch name for all projects
- Unit tests
BREAKING CHANGE: Branch name is required in all projects
> feat: Branch name is required for database initialization

- src/__tests__/tigris.utility.spec.ts
- src/collection.ts
- src/search/types.ts
- src/types.ts
- src/utility.ts
- src/utils/logger.ts
- Pass an additional `sort` param to `FindQuery`
- Unit tested
TIG-599, TIG-652
> feat: Ability to sort results from read queries

- src/__tests__/tigris.filters.spec.ts
- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.schema.spec.ts
- src/__tests__/tigris.updatefields.spec.ts
- src/__tests__/tigris.utility.spec.ts
- src/types.ts
- src/utility.ts
- Including support for update operations:
```ts
$set?: SimpleUpdateField<T>;
$unset?: Partial<Paths<T>>[];
$increment?: NumericUpdateField<T>;
$decrement?: NumericUpdateField<T>;
$multiply?: NumericUpdateField<T>;
$divide?: NumericUpdateField<T>;
```
- Unit tests
- TIG-812
> feat: Atomic update operations - $increment, $decrement, $multiply etc.

- src/__tests__/tigris.utility.spec.ts
- src/utility.ts
- re-introduce branch name nerfing only for certain characters
- Unit tests
> fix: nerfing logic to only include certain characters

- src/__tests__/tigris.utility.spec.ts
- src/utility.ts
Binary data streamed from server is now UTF8 encoded back to user's model.
Added unit test.
#228
> fix: Fixed reading binary data into UTF8

- README.md
- src/__tests__/tigris.utility.spec.ts
- src/utility.ts
> Beta release

- src/__tests__/fixtures/json-schema/search/orders.json
- src/__tests__/fixtures/schema/search/orders.ts
- src/__tests__/search/schema.spec.ts
- src/__tests__/test-search-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.schema.spec.ts
- src/__tests__/tigris.search.spec.ts
- src/__tests__/utils.ts
- src/consumables/search-iterator.ts
- src/db.ts
- src/decorators/metadata/decorator-meta-storage.ts
- src/decorators/metadata/index-field-metadata.ts
- src/decorators/tigris-index-field.ts
- src/decorators/tigris-index.ts
- src/decorators/utils.ts
- src/index.ts
- src/schema/decorated-schema-processor.ts
- src/search/search.ts
- src/search/types.ts
- src/utility.ts
- Demonstrates Search Index modeling using decorators and interface
- The unit tests are setup to automatically test schema conversions
- For easy review just follow the numbered comments
- Unit tests
> feat: Search Index modeling using decorators

- src/search/search-index.ts
Honor the passed search query string
Tested locally
Issue #246
> The query string was being ignored

- src/__tests__/tigris.rpc.spec.ts
> fix: skipping cache crud test

- src/__tests__/tigris.search.spec.ts
- src/error.ts
- src/search/result.ts
- src/search/types.ts
- Removing getters from classes, instead relying on `readonly` for immutability. This reduces lines of code and makes objects easy to log on console.
- Existing unit tests should cover these
> refactor: removing getters and reducing lines of code

- src/__tests__/fixtures/json-schema/search/matrices.json
- src/__tests__/fixtures/schema/search/matrices.ts
- src/__tests__/search/schema.spec.ts
- Unit test to demonstrate and validate nested arrays in Search Index
> test: search index nested array example

- src/__tests__/fixtures/json-schema/users.json
- src/__tests__/fixtures/json-schema/vacationRentals.json
- src/__tests__/fixtures/schema/movies.ts
- src/__tests__/fixtures/schema/users.ts
- src/__tests__/fixtures/schema/vacationRentals.ts
- src/schema/decorated-schema-processor.ts
- src/types.ts
- src/utility.ts
Add support for secondary indexes in schema. Fixes #258
> feat: Add support for secondary index in schema

- src/__tests__/tigris.rpc.spec.ts
- src/collection.ts
- Fixes the build issues in previous PR #303  ( failed due to prettier)
- Refactored collectionCreatedAtFieldNames to initialize in the constructor for performance.
https://github.com/tigrisdata/tigris-client-ts/pull/303#discussion_r1167027889
> refactor:  initializing collectionCreatedAtFieldNames in constructor for performance

- src/__tests__/test-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/utility.ts
- When we are deserializing the JSON String to Object, added a check if it's a string and the value in ISO string format, then convert the key value into Date object.
/claim #227
- Added specific test cases.
Fixes #227
> fix: deserialize to date object from string

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- src/__tests__/test-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/collection.ts
- src/types.ts
Adds the new explain endpoint that explains what the query planner would do for a query.
Test should pass 
closes #311
> feat: add explain endpoint

- src/__tests__/tigris.utility.spec.ts
- src/search/query.ts
- src/types.ts
- src/utility.ts
- Added GroupBy option to searchQuery
Fixes #262
> feat: groupBy option for Index Search

- src/__tests__/test-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/search/result.ts
- Group by support for search queries
- Added groupedHits to the search result.
- Closes #317 
and link here as `tigrisdata/tigris-docs#123`_
> feat: group by option for search queries

- README.md
- src/__tests__/test-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/collection.ts
- src/types.ts
- Related Issue #323
- Closes #
> fix: ci build fixes

- src/types.ts
Remove special typing for $contains in SelectorField<T> type alias
- Related Issue #331
- Closes #331
> update SelectorField<T> to remove special typing for $contains queries

- .github/workflows/lint-pr.yaml
- PR title should match conventional commit format
- Closes #
> ci: automate PR title validation

- .eslintrc.json
> fix: turn off failing eslinter

- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- .github/workflows/ts-ci.yml
- package.json
> ci: restructure package.json and fix ci process

- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- package.json
> ci: audit signatures on releases

- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- .github/workflows/ts-ci.yml
- package.json
This won't trigger a release, updating the actions in beta branch so they run from next update onwards.
> Beta code update

- .eslintrc.json
- src/__tests__/utils.ts
- src/consumables/iterable-stream.ts
- src/utils/env-loader.ts
Don't use `node:` style imports as this may not work with older dependency 
- Closes #
> fix: Don't use node: style imports

- README.md
- package.json
- reviewpad.yml
> feat: switching beta branch to publish to beta channel only

- src/tigris.ts
> fix: ping.close() callable externally

- README.md
- package.json
- reviewpad.yml
- src/__tests__/tigris.search.spec.ts
- src/schema/decorated-schema-processor.ts
- src/search/search.ts
- src/tigris.ts
> Minor release

- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.updatefields.spec.ts
- src/types.ts
- src/utility.ts
- New field operator `$push` for update. ( https://github.com/tigrisdata/tigris/pull/1131)
https://github.com/tigrisdata/tigris/issues/893#issuecomment-1540746041
> feat: $push field operator for update

- src/__tests__/tigris.search.spec.ts
- src/search/search.ts
> fix: no remote call when instantiating search index

- src/__tests__/tigris.readfields.spec.ts
- src/__tests__/tigris.utility.spec.ts
- src/collection.ts
- src/search/query.ts
- src/types.ts
- src/utility.ts
Reverts tigrisdata/tigris-client-ts#350
> fix: Revert "feat: static type binding for query"

- package-lock.json
- package.json
- src/__tests__/test-search-service.ts
- src/__tests__/test-service.ts
- src/__tests__/tigris.rpc.spec.ts
- src/__tests__/tigris.search.spec.ts
- src/tigris.ts
- All search and database requests will be retried for status codes in ["UNAVAILABLE", "UNKNOWN"]
- https://grpc.github.io/grpc/core/md_doc_statuscodes.html
> fix: GRPC Retry on transient failure
